name = "dharma-trans-api"
main = "index.js"
compatibility_date = "2024-04-16"

[[r2_buckets]]
  binding = "MY_R2_BUCKET"
  bucket_name = "aitrans"

# If you need environment variables (like API keys for external services later)
[vars]
 OPENROUTER_KEY = "my-variable"

# If you need secrets (like CLOUDFLARE_AUTH_TOKEN if you use the AI API later)
# [[unsafe.bindings]]
# name = "SECRETS"
# type = "secret_text"
# text = "CLOUDFLARE_AUTH_TOKEN"
