name = "dharma-trans-api"
main = "index.js"
compatibility_date = "2024-04-16"


[r2_buckets]
binding = "my_r2_bucket"  # Name of the binding used in code
bucket_name = "aitrans"  # Your actual R2 bucket name